model:
  model_name_or_path: "/home/nwliu/data/dvagen/ckpt/qwen3-0.6b_qwen3-0.6b/checkpoint-20000"
  language_model_path: "/home/nwliu/data/dvagen/ckpt/qwen3-0.6b_qwen3-0.6b/checkpoint-20000/lm_tokenizer"
  phrase_encoder_path: "/home/nwliu/data/dvagen/ckpt/qwen3-0.6b_qwen3-0.6b/checkpoint-20000/phrase_tokenizer"
  phrase_encoder_batch_size: 100000

infer:
  doc_top_k: 32
  embedding_model_path: "/home/nwliu/public/pretrain/Qwen/Qwen3-Embedding-0.6B"
  vector_store_path: "/home/nwliu/data/dvagen/index"
  do_sample: true
  max_new_tokens: 128
  temperature: 0.7
  top_k: 50

eval:
  eval_seed: 0
  test_data_file: "/home/nwliu/data/dvagen/data/wikitext-103/test.txt"
  batch_size: 8
  task_type: "LANGUAGE_MODELING"
  save_results_path: "/home/nwliu/data/dvagen/results/wikitext-103_qwen3-0.6b_qwen3-0.6b_greedy.json"
  prefix_tokenizer_path: "/home/nwliu/public/old_pretrain/gpt2"
  prefix_tokens: 32
  mauve_model_path: "/home/nwliu/public/old_pretrain/gpt2-large"
  mauve_batch_size: 8
  perplexity_model_path: "/home/nwliu/public/old_pretrain/gpt2-large"
  perplexity_batch_size: 8
  nsl_tokenizer_path: "/home/nwliu/public/pretrain/Qwen/Qwen3-0.6B-Base"